#!/usr/bin/env python3

from sys import argv, exit
from src.parsing import check_errors
from src.construction import construction

def main():
    rt = check_errors(argv)
    if (rt == 1):
        return 0
    if (rt == 84):
        return 84
    construction(rt)
    return (0)

if __name__ == "__main__":
    exit(main())
