#!/usr/bin/env python3

from sys import argv, exit
import math

def print_help():
    print("USAGE")
    print("\t./303make makefile [file]")
    print("DESCRIPTION")
    print("\tmakefile\tname of the makefile")
    print("\tfile\t\tname of a recently modified file")
    return (0)

def main():
    if (len(argv) == 2 and argv[1] == "-h"):
        print_help()
        return (0)
    return (0)

if __name__ == "__main__":
    exit(main())
