#!/usr/bin/env python3

from sys import argv, exit
from src.parsing import check_errors
from src.commands import commands
from src.matrix import matrix

def main():
    rt = check_errors(argv)
    if (rt == 84):
        return 84
    if (rt == 1):
        return 0
    if (rt == 2):
        rt = matrix(argv)
        if (rt == 84):
            return 84
    if (len(argv) == 3):
        rt = commands(argv)
        if (rt == 84):
            return 84

if __name__ == "__main__":
    exit(main())
