#!/usr/bin/env python3

from sys import argv, exit
from src.parsing import check_error
from src.pipes import pipes

def main():
    if (check_error(argv) == 84):
        return (84)
    pipes(argv)
    return (0)

if __name__ == "__main__":
    exit(main())
