#!/usr/bin/env python3

from sys import argv, exit
from src.parsing import check_error
from src.pathfinding import pathfinding

def main():
    if (check_error(argv) == 84):
        return (84)
    pathfinding(argv)
    return (0)

if __name__ == "__main__":
    exit(main())
