#!/usr/bin/env python3

from sys import argv, exit

from src.check_errors import check_errors, print_help
from src.multigrains import multigrains

def main():
    if (len(argv) != 10):
        check_errors(argv)
    if (len(argv) == 2 and argv[1] == "-h"):
        print_help()
        return 0
    multigrains(argv)
    return 0

if __name__ == "__main__":
    exit(main())
