#!/usr/bin/env python3

from sys import argv, exit
import math
from src.parsing import print_help
from src.parsing import check_error

def main():
    if (len(argv) == 2 and argv[1] == "-h"):
        print_help()
        return (0)
    if (check_error(argv) == 84):
        return (84)
    return (0)

if __name__ == "__main__":
    exit(main())
