#!/usr/bin/env python3

from sys import argv, exit
import math

def print_help():
    print("USAGE")
    print("\t./309pollution n file x y")
    print("DESCRIPTION")
    print("\tn\tnumber of points on the grid axis")
    print("\tfile\tcsc file containing the data points x;y;p")
    print("\tx\tabscissa of the point whose pollution level we want to know")
    print("\ty\tordinate of the point whose pollution level we want to know")
    return (0)

def main():
    if (len(argv) == 2 and argv[1] == "-h"):
        print_help()
        return (0)
    return (0)

if __name__ == "__main__":
    exit(main())
