#!/usr/bin/env python3

from sys import argv, exit
import math

def print_help():
    print("USAGE")
    print("\t./306radiator n ir jr [i j]")
    print("")
    print("DESCRIPTION")
    print("\tn\t\tsize of the room")
    print("\t(ir, jr)\tcoordinates of the radiator")
    print("\t(i, j)\t\tcoordinates of a point in the room")
    return (0)

def main():
    if (len(argv) == 2 and argv[1] == "-h"):
        print_help()
        return (0)
    return (0)

if __name__ == "__main__":
    exit(main())
